name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "0.11.28"
          enable-cache: true
      - name: Install Python
        run: uv python install 3.14
      - name: Install dependencies
        run: |
          uv sync --all-extras --frozen
          uv pip install drf-spectacular
      - name: Run checks
        run: uv run make check
      - name: Run tests and create coverage report
        run: uv run make test-coverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        deps:
          - fastapi starlette
          - fastapi==0.116.1 starlette
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: "0.11.28"
          enable-cache: true
      - name: Install Python
        run: uv python install ${{ matrix.python }}
      - name: Build Python package wheel
        run: uv build --wheel
      - name: Install test dependencies
        run: uv sync --no-install-project --only-group test --frozen
      - name: Install app dependencies
        run: uv pip install ${{ matrix.deps }} ./dist/apitally_serverless-*.whl
      - name: Run tests
        run: uv run make test

  ci-gate:
    needs:
      - test-coverage
      - test-matrix
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed or skipped
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
